build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-toplevel-reference-genome-ensembl-v1
  version: '1'
requirements:
  build:
  - samtools
  - zlib
  run:
  - samtools
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - Top-Level
  - Release-99
  - ref
  - reference
  - Ensembl-ref
  - DNA-Seqeunce
  - Fasta-Seqeunce
  - fasta-file
  summary: The GRCh38 unmasked genomic DNA seqeunce reference genome from Ensembl-Release
    99. Includes all sequence regions flagged as toplevel by Ensembl including chromosomes,
    regions not assembled into chromosomes, and N padded haplotype/patch regions.
    'Top Level file'
  tags:
    data-provider: Ensembl
    data-version: release-99_11-18-19
    file-type:
    - fa
    final-file-sizes:
      grch38-toplevel-reference-genome-ensembl-v1.fa.gz: 1.29G
      grch38-toplevel-reference-genome-ensembl-v1.fa.gz.fai: 27.85K
      grch38-toplevel-reference-genome-ensembl-v1.fa.gz.gzi: 15.74M
    final-files:
    - grch38-toplevel-reference-genome-ensembl-v1.fa.gz
    - grch38-toplevel-reference-genome-ensembl-v1.fa.gz.fai
    - grch38-toplevel-reference-genome-ensembl-v1.fa.gz.gzi
    genomic-coordinate-base: NA
    ggd-channel: genomics
