build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files: []
package:
  name: hg19-structural-variants-gnomad-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - hg19-chrom-mapping-ensembl2ucsc-ncbi-v1
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - sv
  - gnomAD
  - structural-variants
  - vcf-file
  summary: SV callset 2.1 from gnomAD. Remapped from Ensembl GRCh37 to UCSC hg19
  tags:
    data-provider: gnomad
    data-version: 2.1.1
    file-type:
    - vcf
    final-file-sizes:
      hg19-structural-variants-gnomad-v1.sites.vcf.gz: 141.05M
      hg19-structural-variants-gnomad-v1.sites.vcf.gz.tbi: 451.90K
    final-files:
    - hg19-structural-variants-gnomad-v1.sites.vcf.gz
    - hg19-structural-variants-gnomad-v1.sites.vcf.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
