build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-cpg-islands-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch37-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - CpG
  - region
  - bed-file
  - cpg-islands
  - islands
  summary: cpg islands from UCSC in bed format. Remapped from UCSC hg19 to Ensembl
    GRCh37. Any scaffoldings that are not in the GRCh37.genome file or that cannot
    be remapped are removed
  tags:
    data-provider: UCSC
    data-version: 22-Mar-2020
    file-type:
    - bed
    final-file-sizes:
      grch37-cpg-islands-ucsc-v1.bed.gz: 614.42K
      grch37-cpg-islands-ucsc-v1.bed.gz.tbi: 185.26K
    final-files:
    - grch37-cpg-islands-ucsc-v1.bed.gz
    - grch37-cpg-islands-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
