build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files: []
package:
  name: hg19-structural-variants-database-genomic-variants-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - structural-variants
  - structural-variant
  - SVs
  - SV
  - dbVar
  - dbvar
  summary: Database of Genomic Variants incorporating dbVar, July 2013 and later
  tags:
    data-provider: UCSC
    data-version: '2020-01-13'
    file-type:
    - bed
    final-file-sizes:
      hg19-structural-variants-database-genomic-variants-ucsc-v1.bed.gz: 74.51M
      hg19-structural-variants-database-genomic-variants-ucsc-v1.bed.gz.tbi: 216.71K
    final-files:
    - hg19-structural-variants-database-genomic-variants-ucsc-v1.bed.gz
    - hg19-structural-variants-database-genomic-variants-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
