build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-known-genes-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch38-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - KnownGenes
  - gene-features
  - UCSC-Genes
  - protein-coding-genes
  - non-coding-RNA-genes
  - long-non-coding-RNA
  - small-non-coding-RNA
  - pseduogenes
  - immunoglobulin
  - GENCODE-v32-genes
  summary: The 'KnownGene' track from UCSC. Comprised of all gene models from GENCODE
    v32. Includes protein-coding genes, non-coding RNA genes, and pseudo-genes. Gene
    symbols and gene descriptions have been added to the dataset. Remapped from UCSC
    hg38 to Ensembl GRCh38
  tags:
    data-provider: UCSC
    data-version: 13-Oct-2019
    file-type:
    - bed
    final-file-sizes:
      grch38-known-genes-ucsc-v1.bed.gz: 13.64M
      grch38-known-genes-ucsc-v1.bed.gz.tbi: 217.99K
    final-files:
    - grch38-known-genes-ucsc-v1.bed.gz
    - grch38-known-genes-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
