build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: arq5x
  extra-files:
  - hg38-chromsizes-ggd-v1.txt
package:
  name: hg38-chromsizes-ggd-v1
  version: '1'
requirements:
  build: []
  run: []
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - genome
  - chromosome
  - lengths
  - sizes
  summary: Chromosome lengths for hg38
  tags:
    data-provider: GGD
    data-version: 16-Apirl-2020
    file-type:
    - txt
    final-file-sizes:
      hg38-chromsizes-ggd-v1.txt: 15.53K
    final-files:
    - hg38-chromsizes-ggd-v1.txt
    genomic-coordinate-base: NA
    ggd-channel: genomics
