build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-coding-exons-gencode-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - hg38-chrom-mapping-ensembl2ucsc-ncbi-v1
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - Gene-Features
  - GTF
  - GENOCDOE-GTF
  - GENCODE-Gene-Sets
  - Annotated-Transcripts
  - Protein-Coding-Exon-Features
  - Coding-Exon
  - Protein-Coding-Exons
  summary: 'Exon Coding Features. Exons that overlap coding regions in protein coding
    genes. Features are from the comprehensive set of gene annotations including reference
    chromosomes, scaffoldings, assembly patches, and alternative loci. All other features,
    including non-coding exon features and non-protein coding exon features, have
    been removed. Data is specific to GENCODE Release 34 (Ensembl 100). Features include:
    exon (exons that overlap coding regions in protein coding genes). Remapped from
    Ensembl GRCh38 to UCSC hg38.'
  tags:
    data-provider: GENCODE
    data-version: release-34_03-24-2020
    file-type:
    - gtf
    final-file-sizes:
      hg38-coding-exons-gencode-v1.gtf.gz: 18.32M
      hg38-coding-exons-gencode-v1.gtf.gz.tbi: 506.61K
    final-files:
    - hg38-coding-exons-gencode-v1.gtf.gz
    - hg38-coding-exons-gencode-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
