build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-reference-genome-ucsc-v1
  version: '1'
requirements:
  build:
  - htslib
  - samtools
  - zlib
  run:
  - htslib
  - samtools
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - ref
  - reference-genome
  - fasta-file
  - soft-masked
  summary: The hg38 soft masked genomic DNA seqeunce reference genome from UCSC (patch
    12). Repeats found by 'RepeatMasker' and 'Tandem Repeat Finder' are shown as lower
    case. Non repeating seqeunce are shown as upper case.
  tags:
    data-provider: UCSC
    data-version: 10-Aug-2018
    file-type:
    - fa
    final-file-sizes:
      hg38-reference-genome-ucsc-v1.fa.gz: 1.02G
      hg38-reference-genome-ucsc-v1.fa.gz.fai: 25.61K
      hg38-reference-genome-ucsc-v1.fa.gz.gzi: 814.34K
    final-files:
    - hg38-reference-genome-ucsc-v1.fa.gz
    - hg38-reference-genome-ucsc-v1.fa.gz.fai
    - hg38-reference-genome-ucsc-v1.fa.gz.gzi
    genomic-coordinate-base: NA
    ggd-channel: genomics
