build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: jrb
  extra-files: []
package:
  name: grch38-reference-genome-gencode-v1
  version: '1'
requirements:
  build:
  - htslib
  - samtools
  - samtools>=1.10
  - zlib
  run:
  - htslib
  - samtools
  - samtools>=1.10
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - reference
  - primary-assembly
  - gencode
  - fasta
  summary: Genome sequence, primary assembly. Nucleotide sequence of the GRCh38 primary
    genome assembly (chromosomes and scaffolds)
  tags:
    data-provider: GENCODE
    data-version: release-34
    file-type:
    - fa
    final-file-sizes:
      grch38-reference-genome-gencode-v1.fa.gz: 894.51M
      grch38-reference-genome-gencode-v1.fa.gz.fai: 6.41K
      grch38-reference-genome-gencode-v1.fa.gz.gzi: 772.41K
    final-files:
    - grch38-reference-genome-gencode-v1.fa.gz
    - grch38-reference-genome-gencode-v1.fa.gz.fai
    - grch38-reference-genome-gencode-v1.fa.gz.gzi
    genomic-coordinate-base: NA
    ggd-channel: genomics
