build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-reference-genome-gencode-v1
  version: '1'
requirements:
  build:
  - htslib
  - samtools
  - zlib
  run:
  - htslib
  - samtools
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - Reference-Genome
  - Fasta
  - DNA-Sequence
  - GENCODE-34
  - Fasta-sequence
  summary: The GRCh38, patch13, DNA nucleotide sequence for all regions including
    reference chromomsomes, scaffoldings, assembly patches, and haplotypes.
  tags:
    data-provider: GENCODE
    data-version: release-34,patch-13
    file-type:
    - fa
    final-file-sizes:
      grch38-reference-genome-gencode-v1.fa.gz: 942.24M
      grch38-reference-genome-gencode-v1.fa.gz.fai: 21.95K
      grch38-reference-genome-gencode-v1.fa.gz.gzi: 814.12K
    final-files:
    - grch38-reference-genome-gencode-v1.fa.gz
    - grch38-reference-genome-gencode-v1.fa.gz.fai
    - grch38-reference-genome-gencode-v1.fa.gz.gzi
    genomic-coordinate-base: NA
    ggd-channel: genomics
