build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-cancer-genes-futreal-v1
  version: '1'
requirements:
  build:
  - bedtools
  - gsort
  - htslib
  - zlib
  run:
  - bedtools
  - grch38-gene-features-ensembl-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - Cancer
  - cancer-genes
  - genes
  - Futreal
  - gene-set
  summary: 'CDS region genomic coordinates, along with complement coordinates, for
    a manually curated set of cancer genes from Futreal et al. https://www.nature.com/articles/nrc1299.
    Gene symbols manually extracted from the supplemental PDF table here: https://media.nature.com/original/nature-assets/nrc/journal/v4/n3/extref/nrc1299-S1.pdf.
    Gene symbols manually translated to HGNC nomeclature.'
  tags:
    data-provider: Futreal
    data-version: 01-March-2004
    file-type:
    - bed
    final-file-sizes:
      grch38-cancer-genes-futreal-v1.bed.gz: 49.01K
      grch38-cancer-genes-futreal-v1.bed.gz.tbi: 13.70K
      grch38-cancer-genes-futreal-v1.compliment.bed.gz: 31.01K
      grch38-cancer-genes-futreal-v1.compliment.bed.gz.tbi: 19.96K
    final-files:
    - grch38-cancer-genes-futreal-v1.bed.gz
    - grch38-cancer-genes-futreal-v1.bed.gz.tbi
    - grch38-cancer-genes-futreal-v1.compliment.bed.gz
    - grch38-cancer-genes-futreal-v1.compliment.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
