build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-microsatellites-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - microsatellites
  - microsats
  - STR
  - STRs
  - short-tandem-repeat
  - repeats
  - repeat-regions
  summary: Microsatellites from UCSC. Region which tend to be highly polymorphic and
    with at least 15 di- or tri-nucletodie repeats
  tags:
    data-provider: UCSC
    data-version: 28-Nov-2010
    file-type:
    - bed
    final-file-sizes:
      hg19-microsatellites-ucsc-v1.bed.gz: 401.08K
      hg19-microsatellites-ucsc-v1.bed.gz.tbi: 298.03K
    final-files:
    - hg19-microsatellites-ucsc-v1.bed.gz
    - hg19-microsatellites-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
