build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-transcript-only-features-gencode-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch38-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - Gene-Features
  - GTF
  - GENOCDOE-GTF
  - GENCODE-Gene-Sets
  - Annotated-Transcripts
  - Transcript-Only-Features
  summary: 'Transcript only features from the comprehensive set of gene annotations
    including reference chromosomes, scaffoldings, assembly patches, and alternative
    loci. All other features have been removed. Data is specific to GENCODE Release
    34 (Ensembl 100). Features include: transcript.'
  tags:
    data-provider: GENCODE
    data-version: release-34_03-24-2020
    file-type:
    - gtf
    final-file-sizes:
      grch38-transcript-only-features-gencode-v1.gtf.gz: 9.83M
      grch38-transcript-only-features-gencode-v1.gtf.gz.tbi: 228.14K
    final-files:
    - grch38-transcript-only-features-gencode-v1.gtf.gz
    - grch38-transcript-only-features-gencode-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
