build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: arq5x
  extra-files:
  - grch37-chromsizes-ggd-v1.txt
package:
  name: grch37-chromsizes-ggd-v1
  version: '1'
requirements:
  build: []
  run: []
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - genome
  - chromosome
  - lengths
  - sizes
  summary: Chromosome lengths for GRCh37
  tags:
    data-provider: GGD
    data-version: 11-Oct-2019
    file-type:
    - chromsizes
    final-files:
    - grch37-chromsizes-ggd-v1.txt
    genomic-coordinate-base: NA
    ggd-channel: genomics
