build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files: []
package:
  name: hg38-consensus-pseudogene-annotations-chr-regions-gencode-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch38-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - gencode
  - pseudogene
  - pseudogenes
  - yale
  - UCSC
  - consensus
  - consensus-pseudogene
  - consensus-pseudogenes
  - annotation
  - gtf
  summary: Consensus pseudogenes predicted by the Yale and UCSC pipelines. 2-way consensus
    (retrotransposed) pseudogenes predicted by the Yale and UCSC pipelines, but not
    by HAVANA, on the reference chromosomes. This dataset does not form part of the
    main annotation file.
  tags:
    data-provider: GENCODE
    data-version: release-34
    file-type:
    - gtf
    final-file-sizes:
      hg38-consensus-pseudogene-annotations-chr-regions-gencode-v1.gtf.gz: 360.60K
      hg38-consensus-pseudogene-annotations-chr-regions-gencode-v1.gtf.gz.tbi: 103.54K
    final-files:
    - hg38-consensus-pseudogene-annotations-chr-regions-gencode-v1.gtf.gz
    - hg38-consensus-pseudogene-annotations-chr-regions-gencode-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
