build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-protein-coding-features-gencode-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - Gene-Features
  - GTF
  - GENOCDOE-GTF
  - GENCODE-Gene-Sets
  - Annotated-Transcripts
  - Protein-Coding-Features
  summary: 'Protein Coding Features based on feature''s gene biotype from the comprehensive
    set of gene annotations created on GRCh38 and mapped to GRCh37 by GENCODE (v34lift37).
    All non-protein coding features have been removed. Some annotations were obtained
    from GENCODE v19 when mapping failed. Scaffoldings, assenbly patches, and alternative
    loci are NOT included. Features include: CDS, Selenocysteine, UTR, exon, gene,
    start_codon, stop_codon, transcript. Remapped from Ensembl GRCh37 to UCSC hg19'
  tags:
    data-provider: GENCODE
    data-version: release-34_03-24-2020
    file-type:
    - gtf
    final-file-sizes:
      hg19-protein-coding-features-gencode-v1.gtf.gz: 60.36M
      hg19-protein-coding-features-gencode-v1.gtf.gz.tbi: 244.54K
    final-files:
    - hg19-protein-coding-features-gencode-v1.gtf.gz
    - hg19-protein-coding-features-gencode-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
