build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-utr-only-features-gencode-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - Gene-Features
  - GTF
  - GENOCDOE-GTF
  - GENCODE-Gene-Sets
  - Annotated-Transcripts
  - UTR-Only-Features
  - Five-Prime-UTR
  - Three-Prime-UTR
  summary: 'UTR only features from the comprehensive set of gene annotations created
    on GRCh38 and mapped to GRCh37 by GENCODE (v34lift37). All other features have
    been removed. UTRs have been designated as 5'' UTRs or 3'' UTRs based on the coding
    region and strand of the associated gene. Features include: five_prime_utr, three_prime_utr.
    Some annotations were obtained from GENCODE v19 when mapping failed. Scaffoldings,
    assembly patches, and alternative loci are NOT included. Remapped from Ensembl
    GRCh37 to UCSC hg19'
  tags:
    data-provider: GENCODE
    data-version: release-34_03-24-2020
    file-type:
    - gtf
    final-file-sizes:
      hg19-utr-only-features-gencode-v1.gtf.gz: 11.98M
      hg19-utr-only-features-gencode-v1.gtf.gz.tbi: 408.72K
    final-files:
    - hg19-utr-only-features-gencode-v1.gtf.gz
    - hg19-utr-only-features-gencode-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
