build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 4
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-evofold-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - mRNA
  - secondary-structure
  - evofold
  - UCSC
  - conserved
  - bed-file
  summary: The evolutionary conserved mRNA secondary structure predictions hosted
    on UCSC. In bed format
  tags:
    data-provider: UCSC
    data-version: 26-Dec-2010
    file-type:
    - bed
    final-file-sizes:
      hg19-evofold-ucsc-v1.bed.gz: 3.21M
      hg19-evofold-ucsc-v1.bed.gz.tbi: 279.12K
    final-files:
    - hg19-evofold-ucsc-v1.bed.gz
    - hg19-evofold-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
