build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-protein-coding-features-ensembl-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - Gene-Features
  - GTF
  - Ensembl-GTF
  - Ensembl-Gene-Set
  - Annotated-Transcripts
  - Protein-Coding-Features
  summary: 'Protein Coding Features based on feature''s gene biotype from Ensembl
    gene sets. All non-protein coding features have been removed. (Alignment based
    annotation using proteins, cDNA, RNA-seq, etc.). Features include: CDS, Selenocysteine,
    UTR, exon, gene, start_codon, stop_codon, transcript. Features are in GTF format.'
  tags:
    data-provider: Ensembl
    data-version: release-75_2-6-14
    file-type:
    - gtf
    final-file-sizes:
      grch37-protein-coding-features-ensembl-v1.gtf.gz: 35.31M
      grch37-protein-coding-features-ensembl-v1.gtf.gz.tbi: 228.59K
    final-files:
    - grch37-protein-coding-features-ensembl-v1.gtf.gz
    - grch37-protein-coding-features-ensembl-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
