build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files:
  - grch38-phastcons-ucsc-v1.bedGraph.bw
package:
  name: grch38-phastcons-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - ucsc-bigwigtobedgraph
  - zlib
  run:
  - gsort
  - htslib
  - ucsc-bigwigtobedgraph
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - phastCons
  - conservation
  - phastCons-Hmm
  - conservation-scores
  - genome-conservation
  - bigwig
  - bedgraph
  summary: Conservation scores based on the phastcons HMM algorithm against multi-aligned
    sequences of 100 different species. Remapped from UCSC hg38 to Ensembl GRCh38
  tags:
    data-provider: UCSC
    data-version: 08-May-2015
    file-type:
    - bedGraph.gz
    - bedGraph.gz.tbi
    - bw
    final-file-sizes:
      grch38-phastcons-ucsc-v1.bedGraph.bw: 13.67G
      grch38-phastcons-ucsc-v1.bedGraph.gz: 11.86G
      grch38-phastcons-ucsc-v1.bedGraph.gz.tbi: 7.11K
    final-files:
    - grch38-phastcons-ucsc-v1.bedGraph.bw
    - grch38-phastcons-ucsc-v1.bedGraph.gz
    - grch38-phastcons-ucsc-v1.bedGraph.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
