build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-protein-coding-features-gencode-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch38-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - Gene-Features
  - GTF
  - GENOCDOE-GTF
  - GENCODE-Gene-Sets
  - Annotated-Transcripts
  - Protein-Coding-Features
  summary: 'Protein Coding Features based on feature''s gene biotype from the comprehensive
    set of gene annotations including reference chromosomes, scaffoldings, assembly
    patches, and alternative loci. All non-protein coding features have been removed.
    Data is specific to GENCODE Release 34 (Ensembl 100). Features include: CDS, Selenocysteine,
    UTR, exon, gene, start_codon, stop_codon, transcript.'
  tags:
    data-provider: GENCODE
    data-version: release-34_03-24-2020
    file-type:
    - gtf
    final-file-sizes:
      grch38-protein-coding-features-gencode-v1.gtf.gz: 50.64M
      grch38-protein-coding-features-gencode-v1.gtf.gz.tbi: 261.80K
    final-files:
    - grch38-protein-coding-features-gencode-v1.gtf.gz
    - grch38-protein-coding-features-gencode-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
