build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-utr-only-features-gencode-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch37-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - Gene-Features
  - GTF
  - GENOCDOE-GTF
  - GENCODE-Gene-Sets
  - Annotated-Transcripts
  - UTR-Only-Features
  - Five-Prime-UTR
  - Three-Prime-UTR
  summary: 'UTR only features from the comprehensive set of gene annotations created
    on GRCh38 and mapped to GRCh37 by GENCODE (v34lift37). All other features have
    been removed. UTRs have been designated as 5'' UTRs or 3'' UTRs based on the coding
    region and strand of the associated gene. Some annotations were obtained from
    GENCODE v19 when mapping failed. Scaffoldings, assenbly patches, and alternative
    loci are NOT included. Features include: five_prime_utr, three_prime_utr.'
  tags:
    data-provider: GENCODE
    data-version: release-34_03-24-2020
    file-type:
    - gtf
    final-file-sizes:
      grch37-utr-only-features-gencode-v1.gtf.gz: 11.97M
      grch37-utr-only-features-gencode-v1.gtf.gz.tbi: 408.26K
    final-files:
    - grch37-utr-only-features-gencode-v1.gtf.gz
    - grch37-utr-only-features-gencode-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
