build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files: []
package:
  name: grch38-ccdg-sv-vcf-ccdg-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch38-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - sv
  - ccdg
  - structural-variants
  - sv
  - structural
  - vcf-file
  summary: SV callset 2 from ccdg in grch38
  tags:
    data-provider: ccdg
    data-version: '2'
    file-type:
    - vcf
    final-file-sizes:
      grch38-ccdg-sv-vcf-ccdg-v1.public.v2.vcf.gz: 50.44M
      grch38-ccdg-sv-vcf-ccdg-v1.public.v2.vcf.gz.tbi: 375.58K
    final-files:
    - grch38-ccdg-sv-vcf-ccdg-v1.public.v2.vcf.gz
    - grch38-ccdg-sv-vcf-ccdg-v1.public.v2.vcf.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
