build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files:
  - hg19-scores-by-amino-acid-change-ggd-v1.txt
package:
  name: hg19-scores-by-amino-acid-change-ggd-v1
  version: '1'
requirements:
  build: []
  run: []
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - amion-acid
  - amino-acid-change
  - constraint
  - missense-badness-score
  - blosum-score
  - granthams-score
  - amino-acid-score
  summary: Scores for each amino acid changes from missense badnass, blosum, and granthams
  tags:
    data-provider: ggd
    data-version: '1'
    file-type:
    - txt
    final-file-sizes:
      hg19-scores-by-amino-acid-change-ggd-v1.txt: 4.86K
    final-files:
    - hg19-scores-by-amino-acid-change-ggd-v1.txt
    genomic-coordinate-base: NA
    ggd-channel: genomics
