build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-germline-variants-ensembl-v1
  version: '1'
requirements:
  build:
  - bcftools
  - gsort
  - htslib
  - vt
  - zlib
  run:
  - bcftools
  - grch37-reference-genome-ensembl-v1
  - gsort
  - htslib
  - vt
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - genetic-varaition
  - Germline
  - germline-variants
  - VCF
  - varaint-info
  - Ensembl-variantion
  summary: 'All known germline variants at the time of Ensembl release 75. Conseqeunces
    for each variant are included in the annotation. Decomposed and Normalized. Ensembl
    variant info page can be found at: https://uswest.ensembl.org/info/genome/variation/index.html'
  tags:
    data-provider: Ensembl
    data-version: release-75_2-9-14
    file-type:
    - vcf
    final-file-sizes:
      grch37-germline-variants-ensembl-v1.vcf.gz: 1.25G
      grch37-germline-variants-ensembl-v1.vcf.gz.tbi: 2.13M
    final-files:
    - grch37-germline-variants-ensembl-v1.vcf.gz
    - grch37-germline-variants-ensembl-v1.vcf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
