build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files:
  - grch37-hg002-ont-chr22-giab-v1.bam
  - grch37-hg002-ont-chr22-giab-v1.bam.bai
package:
  name: grch37-hg002-ont-chr22-giab-v1
  version: '1'
requirements:
  build:
  - grch37-reference-genome-ensembl-v1
  - minimap2
  - samtools
  - wget
  run:
  - grch37-reference-genome-ensembl-v1
  - minimap2
  - samtools
  - wget
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - ashkenazi
  - hg002
  - ont
  - nanopore
  - giab
  - chr22
  - bam
  - alignments
  summary: GiaB ONT alignments for chromosome 22 in ashkenazi sample HG002
  tags:
    data-provider: giab
    data-version: 06-03-15
    file-type:
    - bam
    final-files:
    - grch37-hg002-ont-chr22-giab-v1.bam
    - grch37-hg002-ont-chr22-giab-v1.bam.bai
    genomic-coordinate-base: NA
    ggd-channel: genomics
