build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-evofold-ucsc-v1
  version: '1'
requirements:
  build:
  - crossmap
  - gsort
  - htslib
  - zlib
  run:
  - crossmap
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - mRNA
  - secondary-structure
  - evofold
  - UCSC
  - conserved
  - bed-file
  summary: '*Liftover* The evolutionary conserved mRNA secondary structure predictions
    hosted on UCSC. In bed format. Lifted over from UCSC hg19 to UCSC hg38.'
  tags:
    data-provider: UCSC
    data-version: 26-Dec-2010
    file-type:
    - bed
    final-file-sizes:
      hg38-evofold-ucsc-v1.bed.gz: 3.21M
      hg38-evofold-ucsc-v1.bed.gz.tbi: 277.97K
    final-files:
    - hg38-evofold-ucsc-v1.bed.gz
    - hg38-evofold-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
