build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files:
  - hg19-chrom-mapping-ensembl2ucsc-ncbi-v1.txt
package:
  name: hg19-chrom-mapping-ensembl2ucsc-ncbi-v1
  version: '1'
requirements:
  build:
  - bioawk
  run:
  - bioawk
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - Chromosome-mapping
  - mapping
  - chrommapping
  - Ensembl2UCSC
  - scaffolding-ids
  - txt
  - patch-13
  - GRCh37-to-hg19
  summary: A tab delimited file containing scaffolding ids that maps GRCh37 Ensembl(GenBank)
    scaffoldings to hg19 UCSC scaffoldings. This is specific to patch 13 of the GRCh37
    Human genome build. (1st column = Ensembl ids, 2nd column = UCSC ids)
  tags:
    data-provider: NCBI
    data-version: 13-October-2016-(patch13)
    file-type:
    - txt
    final-file-sizes:
      hg19-chrom-mapping-ensembl2ucsc-ncbi-v1.txt: 4.56K
    final-files:
    - hg19-chrom-mapping-ensembl2ucsc-ncbi-v1.txt
    genomic-coordinate-base: NA
    ggd-channel: genomics
