build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: arq5x
  extra-files: []
package:
  name: hg38-microsatellites-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - microsatellites
  - microsats
  - STR
  - STRs
  summary: Microsatellites from UCSC
  tags:
    data-provider: UCSC
    data-version: 28-Nov-2010
    file-type:
    - bed
    final-files:
    - hg38-microsatellites-ucsc-v1.bed.gz
    - hg38-microsatellites-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
