build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-ncbi-refseq-gene-features-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - GTF
  - gene-feature-file
  - NCBI-Refseq
  - Refseq-All
  summary: Gene features for all curated and predicted annotations from the NCBI Refseq
    track from UCSC. (GTF). Refseq ALL. Human protein-coding and non-protein-coding
    genes from NCBI RNA reference seqeunce collection.
  tags:
    data-provider: UCSC
    data-version: 10-Jan-2020
    file-type:
    - gtf
    final-file-sizes:
      hg38-ncbi-refseq-gene-features-ucsc-v1.gtf.gz: 34.69M
      hg38-ncbi-refseq-gene-features-ucsc-v1.gtf.gz.tbi: 356.76K
    final-files:
    - hg38-ncbi-refseq-gene-features-ucsc-v1.gtf.gz
    - hg38-ncbi-refseq-gene-features-ucsc-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
