build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-pfam-domains-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - pfam
  - domains
  - protein
  - protein-domains
  - UCSC
  summary: High quality, manually curated Pfam domain annotation in bed12 format from
    UCSC
  tags:
    data-provider: UCSC
    data-version: 13-Oct-2019
    file-type:
    - bed
    final-file-sizes:
      hg38-pfam-domains-ucsc-v1.bed12.bed.gz: 1.49M
      hg38-pfam-domains-ucsc-v1.bed12.bed.gz.tbi: 156.80K
    final-files:
    - hg38-pfam-domains-ucsc-v1.bed12.bed.gz
    - hg38-pfam-domains-ucsc-v1.bed12.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
