build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-gene-features-with-introns-gencode-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - Gene-Features
  - Gene-Annotations
  - All-Regions
  - GTF
  - GENOCDOE-GTF
  - GENCODE-Gene-Sets
  - Annotated-Transcripts
  - Intron-Features
  - Introns
  summary: 'Comprehensive set of gene anntotations created on GRCh38 and mapped to
    GRCh37 by GENCODE (v34lift37). Intron features for each transcripts have been
    added to the annotation set. Some annotations were obtained from GENCODE v19 when
    mapping failed. Scaffoldings, assenbly patches, and alternative loci are NOT included.
    Features include: gene, transcript, exon, intron,  CDS, UTR, start_codon, stop_codon,
    and Selenocysteine. Remapped from Ensembl GRCh37 to UCSC hg19'
  tags:
    data-provider: GENCODE
    data-version: release-34_03-24-2020
    file-type:
    - gtf
    final-file-sizes:
      hg19-gene-features-with-introns-gencode-v1.gtf.gz: 86.53M
      hg19-gene-features-with-introns-gencode-v1.gtf.gz.tbi: 267.88K
    final-files:
    - hg19-gene-features-with-introns-gencode-v1.gtf.gz
    - hg19-gene-features-with-introns-gencode-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
