build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-canonical-transcript-features-gencode-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - Canonical
  - Canonical-Transcripts
  - Canonical-Isoforms
  - Gene-Features
  - GTF
  - Gene-Features
  - Gene-Annotations
  - GTF
  - GENOCDOE-GTF
  - GENCODE-Gene-Sets
  - Annotated-Transcripts
  summary: 'Protein Coding Canonical Transcript Features for each protein coding gene
    id from GENCODE''s v34 (Ensembl 100) comprehensive set of gene anntotations. Canonical
    Transcripts are determined using the APPRIS annotation dataset. In short, for
    all protein coding transcripts, transcripts are filtered based on APPRIS isoform
    flags. If multiple transcripts of the same gene have equal flags, the isoform
    with the most exons is chosen. If all transcritps for a gene are not annotated
    by APPRIS, the transcript with the most exons is chosen as the canonical transcript.
    APPRIS flag information can be found here: http://appris-tools.org/#/downloads
    or here: https://uswest.ensembl.org/info/genome/genebuild/transcript_quality_tags.html.
    Features include: gene, transcript, exon, CDS, UTR, start_codon, stop_codon, and
    Selenocysteine.'
  tags:
    data-provider: GENCODE
    data-version: release-34_03-24-2020
    file-type:
    - gtf
    final-file-sizes:
      grch38-canonical-transcript-features-gencode-v1.gtf.gz: 10.74M
      grch38-canonical-transcript-features-gencode-v1.gtf.gz.tbi: 262.63K
    final-files:
    - grch38-canonical-transcript-features-gencode-v1.gtf.gz
    - grch38-canonical-transcript-features-gencode-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
