build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-pfam-domains-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - pfam
  - domains
  - protein
  - protein-domains
  - UCSC
  summary: High quality, manually curated Pfam domain annotation in bed12 format from
    UCSC
  tags:
    data-provider: UCSC
    data-version: 16-Apr-2017
    file-type:
    - bed
    final-file-sizes:
      hg19-pfam-domains-ucsc-v1.bed12.bed.gz: 1.41M
      hg19-pfam-domains-ucsc-v1.bed12.bed.gz.tbi: 143.50K
    final-files:
    - hg19-pfam-domains-ucsc-v1.bed12.bed.gz
    - hg19-pfam-domains-ucsc-v1.bed12.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
