build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-clinically-associated-variants-ensembl-v1
  version: '1'
requirements:
  build:
  - bcftools
  - gsort
  - htslib
  - vt
  - zlib
  run:
  - bcftools
  - grch38-reference-genome-ensembl-v1
  - gsort
  - hg38-chrom-mapping-ensembl2ucsc-ncbi-v1
  - hg38-reference-genome-ucsc-v1
  - htslib
  - vt
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - genetic-varaition
  - clincal-variants
  - ClinVar-Associated
  - Clinically-Associated-Variants
  - probable-pathogenic-variant
  - likely-pathogenic-variant
  - pathogenic-variant
  - drug-response-variant
  - histocompatibility
  - VCF
  - varaint-info
  - Ensembl-variantion
  summary: 'All known clinically associated variants at the time of Ensembl release
    99. Any variant in ClinVar classified as probably/likely-pathogenic, pathogenic,
    drug-response, or histocompatibility are included. Decomposed and Normalized.
    Remapped from Ensembl GRCh38 to UCSC hg19. Ensembl variant info page can be found
    at: https://uswest.ensembl.org/info/genome/variation/index.html'
  tags:
    data-provider: Ensembl
    data-version: release-99_11-7-19
    file-type:
    - vcf
    final-file-sizes:
      hg38-clinically-associated-variants-ensembl-v1.vcf.gz: 2.05M
      hg38-clinically-associated-variants-ensembl-v1.vcf.gz.tbi: 105.56K
    final-files:
    - hg38-clinically-associated-variants-ensembl-v1.vcf.gz
    - hg38-clinically-associated-variants-ensembl-v1.vcf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
