build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 4
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-evofold-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch37-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - mRNA
  - secondary-structure
  - evofold
  - UCSC
  - conserved
  - bed-file
  summary: The evolutionary conserved mRNA secondary structure predictions hosted
    on UCSC. In bed format. Remapped from UCSC hg19 to Ensembl GRCh37
  tags:
    data-provider: UCSC
    data-version: 26-Dec-2010
    file-type:
    - bed
    final-file-sizes:
      grch37-evofold-ucsc-v1.bed.gz: 3.20M
      grch37-evofold-ucsc-v1.bed.gz.tbi: 279.01K
    final-files:
    - grch37-evofold-ucsc-v1.bed.gz
    - grch37-evofold-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
