build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files: []
package:
  name: hg38-reference-genome-all-gencode-v1
  version: '1'
requirements:
  build:
  - htslib
  - samtools
  - samtools>=1.10
  - zlib
  run:
  - htslib
  - samtools
  - samtools>=1.10
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - reference
  - all-assembly
  - gencode
  - fasta
  summary: Genome sequence. Nucleotide sequence of the hg38.p13 genome assembly version
    on all regions, including reference chromosomes, scaffolds, assembly patches and
    haplotypes
  tags:
    data-provider: GENCODE
    data-version: release-34,patch-13
    file-type:
    - fa
    final-file-sizes:
      hg38-reference-genome-all-gencode-v1.fa.gz: 943.38M
      hg38-reference-genome-all-gencode-v1.fa.gz.fai: 22.03K
      hg38-reference-genome-all-gencode-v1.fa.gz.gzi: 810.94K
    final-files:
    - hg38-reference-genome-all-gencode-v1.fa.gz
    - hg38-reference-genome-all-gencode-v1.fa.gz.fai
    - hg38-reference-genome-all-gencode-v1.fa.gz.gzi
    genomic-coordinate-base: NA
    ggd-channel: genomics
