build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files: []
package:
  name: grch37-haploinsufficient-genes-dang-v1
  version: '1'
requirements:
  build:
  - bedtools
  - grch37-gtf-ensembl-v1
  - gsort
  - htslib
  - pyexcel
  - pyexcel-xls
  - wget
  - zlib
  run:
  - bedtools
  - grch37-gtf-ensembl-v1
  - gsort
  - htslib
  - pyexcel
  - pyexcel-xls
  - wget
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - haploinsufficient
  - haploinsufficiency
  - dang
  - bed-file
  - genes
  - pathoscore
  summary: 'The haploinsufficient gene set comes from Dang et al. (2008): https://www.nature.com/articles/ejhg2008111.
    They used text-searching and database-mining on Pubmed and OMIM to extract an
    annotated list of human haploinsufficient genes, their associated diseases, and
    functions. In total there are 299 genes.'
  tags:
    data-provider: Dang
    data-version: 04-June-2008
    file-type:
    - bed
    final-files:
    - grch37-haploinsufficient-genes-dang-v1.bed.gz
    - grch37-haploinsufficient-genes-dang-v1.bed.gz.tbi
    - grch37-haploinsufficient-genes-dang-v1.complement.bed.gz
    - grch37-haploinsufficient-genes-dang-v1.complement.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
