build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files: []
package:
  name: hg19-ccdg-sv-bedpe-ccdg-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - hg19-chrom-mapping-ensembl2ucsc-ncbi-v1
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - sv
  - ccdg
  - structural-variants
  - sv
  - structural
  - bedpe-file
  - bed-file
  summary: SV callset 2 from ccdg in grch37, bedpe format
  tags:
    data-provider: ccdg
    data-version: '2'
    file-type:
    - bedpe
    final-file-sizes:
      hg19-ccdg-sv-bedpe-ccdg-v1.public.sorted.v2.bedpe.gz: 32.94M
      hg19-ccdg-sv-bedpe-ccdg-v1.public.sorted.v2.bedpe.gz.tbi: 1.01M
    final-files:
    - hg19-ccdg-sv-bedpe-ccdg-v1.public.sorted.v2.bedpe.gz
    - hg19-ccdg-sv-bedpe-ccdg-v1.public.sorted.v2.bedpe.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
