build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-autosomal-recessive-genes-berg-v1
  version: '1'
requirements:
  build:
  - bedtools
  - grch37-gtf-ensembl-v1
  - gsort
  - htslib
  - zlib
  run:
  - bedtools
  - grch37-gtf-ensembl-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - genes
  - autosomal-recessive
  - disease
  - Berg_et_al
  - AD
  - OMIM
  - gene_coordinates
  - pathoscore
  summary: Genomic coordinates, along with the compliment coordinance, from OMIM disease
    genes (as of June 2011) deemed to follow autosomal recessive inheritance according
    Berg et al, 2013. (https://www.ncbi.nlm.nih.gov/pubmed/22995991)
  tags:
    data-provider: berg
    data-version: 1-15-2013
    file-type:
    - bed
    final-files:
    - grch37-autosomal-recessive-genes-berg-v1.bed.gz
    - grch37-autosomal-recessive-genes-berg-v1.bed.gz.tbi
    - grch37-autosomal-recessive-genes-berg-v1.compliment.bed.gz
    - grch37-autosomal-recessive-genes-berg-v1.compliment.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
