build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-autosomal-dominant-genes-berg-blekhman-v1
  version: '1'
requirements:
  build:
  - bedtools
  - grch37-gtf-ensembl-v1
  - gsort
  - htslib
  - zlib
  run:
  - bedtools
  - grch37-gtf-ensembl-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - genes
  - autosomal-dominant
  - disease
  - Berg_et_al
  - Blekhman_et_al
  - AD
  - OMIM
  - gene_coordinates
  - pathoscore
  summary: 'Genomic coordinates, along with the compliment coordinance, for combined
    set of OMIM disease genes deemed to follow autosomal dominant inheritance. Berg
    et al, 2013:  (https://www.ncbi.nlm.nih.gov/pubmed/22995991). Blekham et al, 2008:
    (https://www.ncbi.nlm.nih.gov/pubmed/18571414)'
  tags:
    data-provider: berg-blekhman
    data-version: 1-15-2013_6-24-2008
    file-type:
    - bed
    final-files:
    - grch37-autosomal-dominant-genes-berg-blekhman-v1.bed.gz
    - grch37-autosomal-dominant-genes-berg-blekhman-v1.bed.gz.tbi
    - grch37-autosomal-dominant-genes-berg-blekhman-v1.compliment.bed.gz
    - grch37-autosomal-dominant-genes-berg-blekhman-v1.compliment.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
