build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files:
  - grch38-p13-chrom-mapping-ucsc2ensembl-ncbi-v1.txt
package:
  name: grch38-p13-chrom-mapping-ucsc2ensembl-ncbi-v1
  version: '1'
requirements:
  build:
  - bioawk
  run:
  - bioawk
  host:
  - bioawk
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - Chromosome-mapping
  - mapping
  - chrommapping
  - UCSC2Ensembl
  - scaffolding-ids
  - hg19-to-GRCh38
  - txt
  summary: A tab delimited file containing scaffolding ids that map between USCS(hg19) and
    Ensembl(GenBank)(GRCh38). This is specific to patch 13 of the GRCh38 Human genome build.
    (1st column = UCSC(hg19) ids, 2nd column = Ensembl(GRCh38) ids)
  tags:
    data-provider: NCBI
    data-version: 14-March-2019-(patch13)
    file-type:
    - txt
    final-files:
    - grch38-p13-chrom-mapping-ucsc2ensembl-ncbi-v1.txt
    genomic-coordinate-base: NA
    ggd-channel: genomics

test:
  commands:
    echo "Head of grch38-p13-chrom-mapping-ucsc2ensembl-ncbi-v1.txt" 
    head $CONDA_ROOT/share/ggd/Homo_sapiens/GRCh38/grch38-p13-chrom-mapping-ucsc2ensembl-ncbi-v1/1/grch38-p13-chrom-mapping-ucsc2ensembl-ncbi-v1.txt
