build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files: []
package:
  name: hg19-ccdg-sv-vcf-ccdg-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - hg19-chrom-mapping-ensembl2ucsc-ncbi-v1
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - sv
  - ccdg
  - structural-variants
  - sv
  - structural
  - vcf-file
  summary: SV callset 2 from ccdg in hg19
  tags:
    data-provider: ccdg
    data-version: '2'
    file-type:
    - vcf
    final-file-sizes:
      hg19-ccdg-sv-vcf-ccdg-v1.public.v2.vcf.gz: 32.13M
      hg19-ccdg-sv-vcf-ccdg-v1.public.v2.vcf.gz.tbi: 442.36K
    final-files:
    - hg19-ccdg-sv-vcf-ccdg-v1.public.v2.vcf.gz
    - hg19-ccdg-sv-vcf-ccdg-v1.public.v2.vcf.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
