build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: jrb
  extra-files: []
package:
  name: grch38-reference-genome-all-gencode-v1
  version: '1'
requirements:
  build:
  - htslib
  - samtools
  - samtools>=1.10
  - zlib
  run:
  - htslib
  - samtools
  - samtools>=1.10
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - reference
  - all-assembly
  - gencode
  - fasta
  summary: Genome sequence. Nucleotide sequence of the GRCh38.p13 genome assembly
    version on all regions, including reference chromosomes, scaffolds, assembly patches
    and haplotypes
  tags:
    data-provider: GENCODE
    data-version: release-34,patch-13
    file-type:
    - fa
    final-file-sizes:
      grch38-reference-genome-all-gencode-v1.fa.gz: 942.24M
      grch38-reference-genome-all-gencode-v1.fa.gz.fai: 21.95K
      grch38-reference-genome-all-gencode-v1.fa.gz.gzi: 814.12K
    final-files:
    - grch38-reference-genome-all-gencode-v1.fa.gz
    - grch38-reference-genome-all-gencode-v1.fa.gz.fai
    - grch38-reference-genome-all-gencode-v1.fa.gz.gzi
    genomic-coordinate-base: NA
    ggd-channel: genomics
