build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 4
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-cpg-islands-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - CpG
  - region
  - bed-file
  - cpg-islands
  - islands
  summary: cpg islands from UCSC in bed format. Scaffoldings that are not contained
    in the hg19.genome file are removed
  tags:
    data-provider: UCSC
    data-version: 22-Mar-2020
    file-type:
    - bed
    final-file-sizes:
      hg19-cpg-islands-ucsc-v1.bed.gz: 621.35K
      hg19-cpg-islands-ucsc-v1.bed.gz.tbi: 186.06K
    final-files:
    - hg19-cpg-islands-ucsc-v1.bed.gz
    - hg19-cpg-islands-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
