build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-knowngene-gene-features-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch38-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - KnownGenes
  - gene-features
  - UCSC-Genes
  - feature-file
  - gene-feature-file
  - 5UTR
  - 3UTR
  - CDS
  - exon
  - start_codon
  - stop_codon
  - transcript
  - GTF
  - GENCODE-v32-genes
  summary: Gene features from the 'KnownGene' track from UCSC. (GTF). Features include
    5UTR, 3UTR, CDS, exon, start_codon, stop_codon, transcript. Features are comprised
    of all gene models from GENCODE v32. IDs correspond to the UCSC knowGene IDs.
    Remapped from UCSC hg38 to Ensembl GRCh38
  tags:
    data-provider: UCSC
    data-version: 10-Jan-2020
    file-type:
    - gtf
    final-file-sizes:
      grch38-knowngene-gene-features-ucsc-v1.gtf.gz: 35.26M
      grch38-knowngene-gene-features-ucsc-v1.gtf.gz.tbi: 339.14K
    final-files:
    - grch38-knowngene-gene-features-ucsc-v1.gtf.gz
    - grch38-knowngene-gene-features-ucsc-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
