build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 4
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-cpg-islands-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - CpG
  - region
  - bed-file
  - cpg-islands
  - islands
  summary: hg38 cpg islands from UCSC in bed format
  tags:
    data-provider: UCSC
    data-version: 11-Mar-2019
    file-type:
    - bed
    final-file-sizes:
      hg38-cpg-islands-ucsc-v1.bed.gz: 672.51K
      hg38-cpg-islands-ucsc-v1.bed.gz.tbi: 202.68K
    final-files:
    - hg38-cpg-islands-ucsc-v1.bed.gz
    - hg38-cpg-islands-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
