build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-cytobands-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch37-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - cytobands
  - ideogram
  - staining
  - chromosome
  - bands
  summary: Approximate locations of Chromosome Bands (cytoBands) located with Giemsa-stained
    chromosomes from UCSC. Remapped from UCSC hg19 to Ensembl GRCh37.
  tags:
    data-provider: UCSC
    data-version: 14-Jun-2009
    file-type:
    - bed
    final-file-sizes:
      grch37-cytobands-ucsc-v1.bed.gz: 6.40K
      grch37-cytobands-ucsc-v1.bed.gz.tbi: 7.12K
    final-files:
    - grch37-cytobands-ucsc-v1.bed.gz
    - grch37-cytobands-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
