build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files: []
package:
  name: grch38-structural-variants-bedpe-ccdg-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch38-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - sv
  - ccdg
  - structural-variants
  - sv
  - structural
  - bedpe-file
  - bed-file
  summary: SV callset 2 from ccdg in hg38, bedpe format
  tags:
    data-provider: ccdg
    data-version: '2'
    file-type:
    - bedpe
    final-file-sizes:
      grch38-structural-variants-bedpe-ccdg-v1.public.sorted.v2.bedpe.gz: 51.98M
      grch38-structural-variants-bedpe-ccdg-v1.public.sorted.v2.bedpe.gz.tbi: 1.22M
    final-files:
    - grch38-structural-variants-bedpe-ccdg-v1.public.sorted.v2.bedpe.gz
    - grch38-structural-variants-bedpe-ccdg-v1.public.sorted.v2.bedpe.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
