build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-cytobands-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - cytobands
  - ideogram
  - staining
  - chromosome
  - bands
  summary: Approximate locations of Chromosome Bands (cytoBands) located with Giemsa-stained
    chromosomes from UCSC
  tags:
    data-provider: UCSC
    data-version: 11-Mar-2019
    file-type:
    - bed
    final-file-sizes:
      hg38-cytobands-ucsc-v1.bed.gz: 11.15K
      hg38-cytobands-ucsc-v1.bed.gz.tbi: 17.25K
    final-files:
    - hg38-cytobands-ucsc-v1.bed.gz
    - hg38-cytobands-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
