build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files:
  - grch38-chrom-mapping-ucsc2refseq-ncbi-v1.txt
package:
  name: grch38-chrom-mapping-ucsc2refseq-ncbi-v1
  version: '1'
requirements:
  build:
  - bioawk
  run:
  - bioawk
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - Chromosome-mapping
  - mapping
  - chrommapping
  - UCSC2RefSeq
  - scaffolding-ids
  - txt
  - patch-13
  summary: A tab delimited file containing scaffolding ids that map hg38 UCSC to GRCh38
    RefSeq scaffoldings. This is specific to patch 13 of the GRCh38 Human genome build.
    (1st column = UCSC ids, 2nd Column = RefSeq ids)
  tags:
    data-provider: NCBI
    data-version: 14-April-2020-(patch13)
    file-type:
    - txt
    final-file-sizes:
      grch38-chrom-mapping-ucsc2refseq-ncbi-v1.txt: 19.31K
    final-files:
    - grch38-chrom-mapping-ucsc2refseq-ncbi-v1.txt
    genomic-coordinate-base: NA
    ggd-channel: genomics
