build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-reference-genome-ensembl-v1
  version: '1'
requirements:
  build:
  - samtools
  - zlib
  run:
  - samtools
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - Primary-Assembly
  - Release-75
  - ref
  - reference
  - Ensembl-ref
  - DNA-Seqeunce
  - Fasta-Seqeunce
  - fasta-file
  summary: The GRCh37 unmasked genomic DNA seqeunce reference genome from Ensembl-Release
    75. Includes all sequence regions EXCLUDING haplotypes and patches. 'Primary Assembly
    file'
  tags:
    data-provider: Ensembl
    data-version: release-75_2-3-14
    file-type:
    - fa
    final-file-sizes:
      grch37-reference-genome-ensembl-v1.fa: 3.15G
      grch37-reference-genome-ensembl-v1.fa.fai: 2.74K
    final-files:
    - grch37-reference-genome-ensembl-v1.fa
    - grch37-reference-genome-ensembl-v1.fa.fai
    genomic-coordinate-base: NA
    ggd-channel: genomics
