build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: arq5x
  extra-files:
  - grch38-chromsizes-ggd-v1.txt
package:
  name: grch38-chromsizes-ggd-v1
  version: '1'
requirements:
  build: []
  run: []
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - genome
  - chromosome
  - lengths
  - sizes
  summary: Chromosome lengths for GRCh38
  tags:
    data-provider: GGD
    data-version: 16-April-2020
    file-type:
    - txt
    final-file-sizes:
      grch38-chromsizes-ggd-v1.txt: 11.14K
    final-files:
    - grch38-chromsizes-ggd-v1.txt
    genomic-coordinate-base: NA
    ggd-channel: genomics
