build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-phenotype-associated-variants-ensembl-v1
  version: '1'
requirements:
  build:
  - bcftools
  - crossmap
  - gsort
  - htslib
  - vt
  - zlib
  run:
  - bcftools
  - crossmap
  - grch37-reference-genome-ensembl-v1
  - grch38-reference-genome-ensembl-v1
  - gsort
  - hg19-chrom-mapping-ensembl2ucsc-ncbi-v1
  - hg19-reference-genome-ucsc-v1
  - htslib
  - vt
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - genetic-varaition
  - pheontype-associated
  - Known-Phenotype
  - Phenotype-Associated-Variants
  - VCF
  - varaint-info
  - Ensembl-variantion
  summary: '**Liftover** All variants at the time of Ensembl release 99 that have
    a known phenotype association. Decomposed and Normalized. Liftover from GRCh38
    to GRCh37. Remapped from Ensembl GRCh37 to UCSC hg19. Ensembl variant info page
    can be found at: https://uswest.ensembl.org/info/genome/variation/index.html'
  tags:
    data-provider: Ensembl
    data-version: release-99_11-7-19
    file-type:
    - vcf
    final-file-sizes:
      hg19-phenotype-associated-variants-ensembl-v1.vcf.gz: 10.60M
      hg19-phenotype-associated-variants-ensembl-v1.vcf.gz.tbi: 195.52K
    final-files:
    - hg19-phenotype-associated-variants-ensembl-v1.vcf.gz
    - hg19-phenotype-associated-variants-ensembl-v1.vcf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
