build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files:
  - hg19-liftover-chain-19-to-38-ucsc-v1.over.chain.gz
package:
  name: hg19-liftover-chain-19-to-38-ucsc-v1
  version: '1'
requirements:
  build:
  - htslib
  - zlib
  run:
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - chain
  - liftover
  - hg38
  - hg19
  - ucsc
  summary: Liftover chain file from UCSC
  tags:
    data-provider: ucsc
    data-version: '1'
    file-type:
    - over.chain.gz
    final-file-sizes:
      hg19-liftover-chain-19-to-38-ucsc-v1.over.chain.gz: 227.70K
    final-files:
    - hg19-liftover-chain-19-to-38-ucsc-v1.over.chain.gz
    genomic-coordinate-base: NA
    ggd-channel: genomics
