build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files:
  - grch37-phastcons-ucsc-v1.bedGraph.bw
package:
  name: grch37-phastcons-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - ucsc-bigwigtobedgraph
  - zlib
  run:
  - gsort
  - htslib
  - ucsc-bigwigtobedgraph
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - phastCons
  - conservation
  - phastCons-Hmm
  - conservation-scores
  - genome-conservation
  - bigwig
  - bedgraph
  summary: Conservation scores based on the phastcons HMM algorithm against multi-aligned
    sequences of 100 different species. Remapped from UCSC hg19 to Ensembl GRCh37.
  tags:
    data-provider: UCSC
    data-version: 09-Feb-2014
    file-type:
    - bedGraph.gz
    - bedGraph.gz.tbi
    - bw
    final-file-sizes:
      grch37-phastcons-ucsc-v1.bedGraph.bw: 13.41G
      grch37-phastcons-ucsc-v1.bedGraph.gz: 11.65G
      grch37-phastcons-ucsc-v1.bedGraph.gz.tbi: 1.93K
    final-files:
    - grch37-phastcons-ucsc-v1.bedGraph.bw
    - grch37-phastcons-ucsc-v1.bedGraph.gz
    - grch37-phastcons-ucsc-v1.bedGraph.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
