build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-structural-variants-ensembl-v1
  version: '1'
requirements:
  build:
  - bcftools
  - gsort
  - htslib
  - zlib
  run:
  - bcftools
  - grch38-reference-genome-ensembl-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - genetic-varaition
  - SV
  - structural-mutations
  - structural-variants
  - VCF
  - varaint-info
  - Ensembl-variantion
  summary: 'All known structural mutations at the time of Ensembl release 99. Remapped
    from Ensembl GRCh38 to UCSC hg38. Ensembl variant info page can be found at: https://uswest.ensembl.org/info/genome/variation/index.html'
  tags:
    data-provider: Ensembl
    data-version: release-99_11-7-19
    file-type:
    - vcf
    final-file-sizes:
      grch38-structural-variants-ensembl-v1.vcf.gz: 225.68M
      grch38-structural-variants-ensembl-v1.vcf.gz.tbi: 270.65K
    final-files:
    - grch38-structural-variants-ensembl-v1.vcf.gz
    - grch38-structural-variants-ensembl-v1.vcf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
