build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-intron-features-gencode-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch37-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - GTF
  - GENCODE-Gene-Sets
  - Annotated-Transcripts
  - Intron-Features
  - Introns
  summary: 'Intron features created from the  comprehensive set of gene anntotations
    created on GRCh38 and mapped to GRCh37 by GENCODE (v34lift37). Intron features
    for each transcripts have been added to the annotation set. All other features
    are removed. Some annotations were obtained from GENCODE v19 when mapping failed.
    Scaffoldings, assenbly patches, and alternative loci are NOT included. Features
    include: intron.'
  tags:
    data-provider: GENCODE
    data-version: release-34_03-24-2020
    file-type:
    - gtf
    final-file-sizes:
      grch37-intron-features-gencode-v1.gtf.gz: 10.62M
      grch37-intron-features-gencode-v1.gtf.gz.tbi: 249.10K
    final-files:
    - grch37-intron-features-gencode-v1.gtf.gz
    - grch37-intron-features-gencode-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
