build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-knowngene-gene-features-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch37-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - KnownGenes
  - gene-features
  - UCSC-Genes
  - feature-file
  - gene-feature-file
  - 5UTR
  - 3UTR
  - CDS
  - exon
  - start_codon
  - stop_codon
  - transcript
  - GTF
  summary: Gene features from the 'KnownGene' track from UCSC. (GTF). Features include
    5UTR, 3UTR, CDS, exon, start_codon, stop_codon, transcript. Features are comprised
    of gene predictions based on data from Refseq, GenBank, CCDS, RFam, and tRNA genes
    tracks. IDs correspond to the UCSC knowGene IDs. Remapped from UCSC hg19 to Ensembl
    GRCh37
  tags:
    data-provider: UCSC
    data-version: 10-Jan-2020
    file-type:
    - gtf
    final-file-sizes:
      grch37-knowngene-gene-features-ucsc-v1.gtf.gz: 17.33M
      grch37-knowngene-gene-features-ucsc-v1.gtf.gz.tbi: 281.64K
    final-files:
    - grch37-knowngene-gene-features-ucsc-v1.gtf.gz
    - grch37-knowngene-gene-features-ucsc-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
