build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-gene-features-gencode-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - Gene-Features
  - Gene-Annotations
  - All-Regions
  - GTF
  - GENOCDOE-GTF
  - GENCODE-Gene-Sets
  - Annotated-Transcripts
  summary: 'Comprehensive set of gene anntotations including reference chromosomes,
    scaffoldings, assebly patches, and alternative loci. Data is specific to GENCODE
    Release 34 (Ensembl 100). Features include: gene, transcript, exon, CDS, UTR,
    start_codon, stop_codon, and Selenocysteine.'
  tags:
    data-provider: GENCODE
    data-version: release-34_03-24-2020
    file-type:
    - gtf
    final-file-sizes:
      grch38-gene-features-gencode-v1.gtf.gz: 60.52M
      grch38-gene-features-gencode-v1.gtf.gz.tbi: 367.33K
    final-files:
    - grch38-gene-features-gencode-v1.gtf.gz
    - grch38-gene-features-gencode-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
