build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-pli-scores-exac-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - hg19-chrom-mapping-ensembl2ucsc-ncbi-v1
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - pLI
  - Probability-of-being-loss-of-function-intolerant
  - Constraint
  - LoF-Intolerance
  - ExAC
  - gene-constraint
  summary: 'The probability of being loss-of-function intolerant (pLI) by gene scores
    from ExAC. See paper at: https://www.nature.com/articles/nature19057. Remapped
    from Ensembl GRCh37 to UCSC hg19'
  tags:
    data-provider: ExAC
    data-version: Aug-31-2017
    file-type:
    - bed
    final-file-sizes:
      hg19-pli-scores-exac-v1.bed.gz: 590.69K
      hg19-pli-scores-exac-v1.bed.gz.tbi: 72.76K
    final-files:
    - hg19-pli-scores-exac-v1.bed.gz
    - hg19-pli-scores-exac-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
