build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-gaps-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - gaps
  - regions
  - gap-locations
  - Assembly-Gaps
  - clone-gaps
  - contig-gaps
  - centromere-gaps
  - telomere-gaps
  - heterochromatin-gaps
  - short-arm-gaps
  summary: Assembly gaps from UCSC in bed fromat. Scaffoldings that are not contained
    in the hg19.genome file are removed
  tags:
    data-provider: UCSC
    data-version: 22-Mar-2020
    file-type:
    - bed
    final-file-sizes:
      hg19-gaps-ucsc-v1.bed.gz: 5.16K
      hg19-gaps-ucsc-v1.bed.gz.tbi: 8.22K
    final-files:
    - hg19-gaps-ucsc-v1.bed.gz
    - hg19-gaps-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
