build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-ncbi-refseq-gene-features-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch37-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - GTF
  - gene-feature-file
  - NCBI-Refseq
  - Refseq-All
  summary: Gene features for all curated and predicted annotations from the NCBI Refseq
    track from UCSC. (GTF). Refseq ALL. Human protein-coding and non-protein-coding
    genes from NCBI RNA reference seqeunce collection. Scaffoldings that are not contained
    in the hg19.genome file are removed. Remapped from UCSC hg19 to Ensembl GRCh37
  tags:
    data-provider: UCSC
    data-version: 10-Jan-2020
    file-type:
    - gtf
    final-file-sizes:
      grch37-ncbi-refseq-gene-features-ucsc-v1.gtf.gz: 14.87M
      grch37-ncbi-refseq-gene-features-ucsc-v1.gtf.gz.tbi: 293.90K
    final-files:
    - grch37-ncbi-refseq-gene-features-ucsc-v1.gtf.gz
    - grch37-ncbi-refseq-gene-features-ucsc-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
