build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 4
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-gaps-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - gaps
  - regions
  - gap-locations
  - Assembly-Gaps
  - clone-gaps
  - contig-gaps
  - centromere-gaps
  - telomere-gaps
  - heterochromatin-gaps
  - short-arm-gaps
  summary: Assembly gaps from UCSC in bed fromat
  tags:
    data-provider: UCSC
    data-version: 11-Mar-2019
    file-type:
    - bed
    final-file-sizes:
      hg38-gaps-ucsc-v1.bed.gz: 9.33K
      hg38-gaps-ucsc-v1.bed.gz.tbi: 10.71K
    final-files:
    - hg38-gaps-ucsc-v1.bed.gz
    - hg38-gaps-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
