about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - ref
  - reference
  summary: GRCh37 reference genome from 1000 genomes
  tags:
    data-version: phase2_reference
    ggd-channel: genomics
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-reference-genome
  version: '1'
requirements:
  build:
  - htslib
  - samtools
  - zlib
  run:
  - htslib
  - samtools
  - zlib
source:
  path: .
