build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-microsatellites-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch38-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - microsatellites
  - microsats
  - STR
  - STRs
  - short-tandem-repeat
  - repeats
  - repeat-regions
  summary: Microsatellites from UCSC. Region which tend to be highly polymorphic and
    with at least 15 di- or tri-nucletodie repeats. Remapped from UCSC hg38 to Ensembl
    GRCh37
  tags:
    data-provider: UCSC
    data-version: 23-Aug-2015
    file-type:
    - bed
    final-file-sizes:
      grch38-microsatellites-ucsc-v1.bed.gz: 405.26K
      grch38-microsatellites-ucsc-v1.bed.gz.tbi: 302.12K
    final-files:
    - grch38-microsatellites-ucsc-v1.bed.gz
    - grch38-microsatellites-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
