build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-self-chain-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - Self-Chain
  - Self-Alignment
  - Repeats
  - low-copy-repeats
  summary: Self chain alignemnts of the human genome with an improved gap scoring
    system. Alignemtns point out areas of duplication wihtin the human genome, with
    the exception of the pseudoautosomal regions on X and Y. From the Human Chained
    Self Alignemnts track on UCSC.
  tags:
    data-provider: UCSC
    data-version: 21-Jun-2020
    file-type:
    - bed
    final-file-sizes:
      hg38-self-chain-ucsc-v1.bed.gz: 800.36M
      hg38-self-chain-ucsc-v1.bed.gz.tbi: 716.61K
    final-files:
    - hg38-self-chain-ucsc-v1.bed.gz
    - hg38-self-chain-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
