build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-canonical-transcript-features-ensembl-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - Canonical
  - Canonical-Transcripts
  - Canonical-Isoforms
  - Gene-Features
  - GTF
  - Ensembl-Gene-Set
  - Annotated-Transcripts
  summary: 'Gene features from Ensembl Release-75 for protein-coding canonical transcripts
    based on the APPRIS transcript annotations. Features include gene, transcript,
    CDS, UTR, exon, start_codon, and stop_codon for all canonical transcripts. Canonical
    transcripts are determined based on APPRIS annotations. In short, for all protein
    coding transcripts, transcripts are filtered based on APPRIS isoform flags. If
    multiple transcripts of the same gene have equal flags, the isoform with the most
    exons is chosen. If all transcritps for a gene annotated by APPRIS are missing
    from the base gtf file no canonical transcript is chosen and the gene is removed.
    APPRIS flag information can be found here: http://appris-tools.org/#/downloads
    or here: https://uswest.ensembl.org/info/genome/genebuild/transcript_quality_tags.html'
  tags:
    data-provider: Ensembl
    data-version: release-75_2-6-14
    file-type:
    - gtf
    final-file-sizes:
      grch37-canonical-transcript-features-ensembl-v1.gtf.gz: 9.31M
      grch37-canonical-transcript-features-ensembl-v1.gtf.gz.tbi: 250.77K
    final-files:
    - grch37-canonical-transcript-features-ensembl-v1.gtf.gz
    - grch37-canonical-transcript-features-ensembl-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
