build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-utr-only-features-ensembl-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - hg19-chrom-mapping-ensembl2ucsc-ncbi-v1
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - Gene-Features
  - GTF
  - Ensembl-GTF
  - Ensembl-Gene-Set
  - Annotated-Transcripts
  - UTR-Only-Features
  - Five-Prime-UTR
  - Three-Prime-UTR
  summary: 'UTR only features from Ensembl gene sets. All other features have been
    removed. (Alignment based annotation using proteins, cDNA, RNA-seq, etc.) UTRs
    have been designated as 5'' UTRs or 3'' UTRs based on the coding region and strand
    of the associated gene.Features include: five_prime_utr, three_prime_utr. Features
    are in GTF format. Remapped from Ensembl GRCh37 to UCSC hg19'
  tags:
    data-provider: Ensembl
    data-version: release-75_2-6-14
    file-type:
    - gtf
    final-file-sizes:
      hg19-utr-only-features-ensembl-v1.gtf.gz: 3.97M
      hg19-utr-only-features-ensembl-v1.gtf.gz.tbi: 393.68K
    final-files:
    - hg19-utr-only-features-ensembl-v1.gtf.gz
    - hg19-utr-only-features-ensembl-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
