about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - gaps
  - region
  summary: Assembly gaps from USCS
  tags:
    data-version: 27-Apr-2009
    ggd-channel: genomics
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-gaps
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
