build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files: []
package:
  name: hg38-amino-acid-sequences-chr-regions-gencode-v1
  version: '1'
requirements:
  build:
  - htslib
  - samtools
  - samtools>=1.10
  - zlib
  run:
  - htslib
  - samtools
  - samtools>=1.10
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - amino
  - amino-acid
  - gencode
  - fasta
  - protein
  - coding
  - protein-coding
  - transcript
  summary: Protein-coding transcript translation sequences. Amino acid sequences of
    coding transcript translations on the reference chromosomes
  tags:
    data-provider: GENCODE
    data-version: release-34
    file-type:
    - fa
    final-file-sizes:
      hg38-amino-acid-sequences-chr-regions-gencode-v1.fa.gz: 12.35M
      hg38-amino-acid-sequences-chr-regions-gencode-v1.fa.gz.fai: 13.57M
      hg38-amino-acid-sequences-chr-regions-gencode-v1.fa.gz.gzi: 12.39K
    final-files:
    - hg38-amino-acid-sequences-chr-regions-gencode-v1.fa.gz
    - hg38-amino-acid-sequences-chr-regions-gencode-v1.fa.gz.fai
    - hg38-amino-acid-sequences-chr-regions-gencode-v1.fa.gz.gzi
    genomic-coordinate-base: NA
    ggd-channel: genomics
