build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-segmental-dups-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch38-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - superdups
  - segdups
  - seg
  - dups
  - duplications
  - UCSC
  - Segmental-Duplication
  summary: Segmental duplications (SuperDups) File from UCSC. That is, duplications
    of at least 1kb total sequence of non-repeatmasker sequence in bed format. Remapped
    from UCSC hg38 to Ensembl GRCh38.
  tags:
    data-provider: UCSC
    data-version: 19-Oct-2014
    file-type:
    - bed
    final-file-sizes:
      grch38-segmental-dups-ucsc-v1.bed.gz: 4.14M
      grch38-segmental-dups-ucsc-v1.bed.gz.tbi: 79.50K
    final-files:
    - grch38-segmental-dups-ucsc-v1.bed.gz
    - grch38-segmental-dups-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
