build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files: []
package:
  name: grch38-polya-annotations-chr-regions-gencode-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch38-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - gencode
  - polya
  - polyadenylation
  - annotation
  - gtf
  summary: PolyA feature annotation. It contains the polyA features (polyA_signal,
    polyA_site, pseudo_polyA) manually annotated by HAVANA on the reference chromosomes.
    This dataset does not form part of the main annotation file
  tags:
    data-provider: GENCODE
    data-version: release-34
    file-type:
    - gtf
    final-file-sizes:
      grch38-polya-annotations-chr-regions-gencode-v1.gtf.gz: 2.02M
      grch38-polya-annotations-chr-regions-gencode-v1.gtf.gz.tbi: 305.73K
    final-files:
    - grch38-polya-annotations-chr-regions-gencode-v1.gtf.gz
    - grch38-polya-annotations-chr-regions-gencode-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
