build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-autosomal-recessive-genes-berg-v1
  version: '1'
requirements:
  build:
  - bedtools
  - gsort
  - htslib
  - zlib
  run:
  - bedtools
  - grch38-gene-features-ensembl-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - genes
  - autosomal-recessive
  - disease
  - Berg_et_al
  - AR
  - OMIM
  - gene_coordinates
  - CDS-regions
  summary: 'CDS region genomic coordinates, along with the compliment coordinates,
    for OMIM disease genes (as of June 2011) deemed to follow autosomal recessive
    inheritance. (Assembled by Macarthur Lab). Berg et al, 2013:  (https://www.ncbi.nlm.nih.gov/pubmed/22995991).'
  tags:
    data-provider: berg
    data-version: 1-15-2013
    file-type:
    - bed
    final-file-sizes:
      grch38-autosomal-recessive-genes-berg-v1.bed.gz: 207.94K
      grch38-autosomal-recessive-genes-berg-v1.bed.gz.tbi: 42.99K
      grch38-autosomal-recessive-genes-berg-v1.compliment.bed.gz: 123.06K
      grch38-autosomal-recessive-genes-berg-v1.compliment.bed.gz.tbi: 32.11K
    final-files:
    - grch38-autosomal-recessive-genes-berg-v1.bed.gz
    - grch38-autosomal-recessive-genes-berg-v1.bed.gz.tbi
    - grch38-autosomal-recessive-genes-berg-v1.compliment.bed.gz
    - grch38-autosomal-recessive-genes-berg-v1.compliment.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
