build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: jrb
  extra-files: []
package:
  name: grch37-gnomad-sv-gnomad-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - sv
  - gnomAD
  - structural-variants
  - vcf-file
  summary: SV callset 2.1 from gnomAD
  tags:
    data-provider: gnomad
    data-version: 2.1.1
    file-type:
    - vcf
    final-file-sizes:
      grch37-gnomad-sv-gnomad-v1.sites.vcf.gz: 140.88M
      grch37-gnomad-sv-gnomad-v1.sites.vcf.gz.tbi: 452.41K
    final-files:
    - grch37-gnomad-sv-gnomad-v1.sites.vcf.gz
    - grch37-gnomad-sv-gnomad-v1.sites.vcf.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
