build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files: []
package:
  name: grch38-cytobands-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - grch38-chrom-mapping-ucsc2ensembl-ncbi-v1
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh38
    species: Homo_sapiens
  keywords:
  - cytobands
  - ideogram
  - staining
  - chromosome
  - bands
  summary: Approximate locations of Chromosome Bands (cytoBands) located with Giemsa-stained
    chromosomes from UCSC. Remapped from UCSC hg38 to Ensembl GRCh38.
  tags:
    data-provider: UCSC
    data-version: 11-Mar-2019
    file-type:
    - bed
    final-file-sizes:
      grch38-cytobands-ucsc-v1.bed.gz: 10.27K
      grch38-cytobands-ucsc-v1.bed.gz.tbi: 16.91K
    final-files:
    - grch38-cytobands-ucsc-v1.bed.gz
    - grch38-cytobands-ucsc-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
