build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-radar-li-lab-stanford-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - RNA-Editing
  - A-to-I
  - Adenosine-to-Inosine
  - ADAR
  - Guanosine
  - RNA-Modification
  - post-transcriptional-modification
  - RADAR
  summary: 'Rigorously Annotated Database of A-to-I RNA Editing (RADAR). A comprehensive
    collection of Adenosine (A) to Inosine (I) editing sites in human transcripts,
    otherwise known as RNA editing sites. Paper: http://nar.oxfordjournals.org/content/42/D1/D109'
  tags:
    data-provider: Li-Lab-Stanford
    data-version: v2_02-Feb-2017
    file-type:
    - bed
    final-file-sizes:
      hg19-radar-li-lab-stanford-v1.bed.gz: 15.28M
      hg19-radar-li-lab-stanford-v1.bed.gz.tbi: 795.62K
    final-files:
    - hg19-radar-li-lab-stanford-v1.bed.gz
    - hg19-radar-li-lab-stanford-v1.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
