build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-autosomal-dominant-genes-blekhman-v1
  version: '1'
requirements:
  build:
  - bedtools
  - gsort
  - htslib
  - zlib
  run:
  - bedtools
  - grch38-gene-features-ensembl-v1
  - gsort
  - hg38-chrom-mapping-ensembl2ucsc-ncbi-v1
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - genes
  - autosomal-dominant
  - disease
  - Blekhman_et_al
  - AD
  - OMIM
  - gene_coordinates
  - CDS-regions
  summary: CDS region genomic coordinates, along with the compliment coordinates,
    for OMIM disease genes deemed to follow autosomal dominant inheritance according
    to extensive manual curation by Molly Przeworski's group.(https://www.ncbi.nlm.nih.gov/pubmed/18571414).
  tags:
    data-provider: blekhman
    data-version: 6-24-2008
    file-type:
    - bed
    final-file-sizes:
      hg38-autosomal-dominant-genes-blekhman-v1.bed.gz: 64.75K
      hg38-autosomal-dominant-genes-blekhman-v1.bed.gz.tbi: 15.01K
      hg38-autosomal-dominant-genes-blekhman-v1.compliment.bed.gz: 43.18K
      hg38-autosomal-dominant-genes-blekhman-v1.compliment.bed.gz.tbi: 20.42K
    final-files:
    - hg38-autosomal-dominant-genes-blekhman-v1.bed.gz
    - hg38-autosomal-dominant-genes-blekhman-v1.bed.gz.tbi
    - hg38-autosomal-dominant-genes-blekhman-v1.compliment.bed.gz
    - hg38-autosomal-dominant-genes-blekhman-v1.compliment.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
