build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-gene-features-ensembl-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - hg19-chrom-mapping-ensembl2ucsc-ncbi-v1
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - Gene-Features
  - GTF
  - Ensembl-GTF
  - Ensembl-Gene-Sets
  - Annotated-Transcripts
  summary: Gene features, including all annotated transcripts, that make up the Ensembl
    gene sets. (Alignment based annotation using proteins, cDNA, RNA-seq, etc.). Features
    are in GTF format. Remapped from Ensembl GRCh37 to UCSC hg19
  tags:
    data-provider: Ensembl
    data-version: release-75_2-6-14
    file-type:
    - gtf
    final-file-sizes:
      hg19-gene-features-ensembl-v1.gtf.gz: 40.46M
      hg19-gene-features-ensembl-v1.gtf.gz.tbi: 325.61K
    final-files:
    - hg19-gene-features-ensembl-v1.gtf.gz
    - hg19-gene-features-ensembl-v1.gtf.gz.tbi
    genomic-coordinate-base: 1-based-inclusive
    ggd-channel: genomics
