build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files:
  - hg38-chromsizes-ncbi-v1.genome
package:
  name: hg38-chromsizes-ncbi-v1
  version: '1'
requirements:
  build: []
  run: []
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - genome
  - chromosome
  - lengths
  - sizes
  - chrom-lengths
  summary: Chromosome lengths for the hg38 genome build from NCBI. (Used to create
    the Go Get Data (GGD) hg38.genome file)
  tags:
    data-provider: NCBI
    data-version: 14-March-2019-(patch13)
    file-type:
    - genome
    final-file-sizes:
      hg38-chromsizes-ncbi-v1.genome: 15.53K
    final-files:
    - hg38-chromsizes-ncbi-v1.genome
    genomic-coordinate-base: NA
    ggd-channel: genomics
