build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-autosomal-dominant-genes-berg-v1
  version: '1'
requirements:
  build:
  - bedtools
  - gsort
  - htslib
  - zlib
  run:
  - bedtools
  - grch38-gene-features-ensembl-v1
  - gsort
  - hg38-chrom-mapping-ensembl2ucsc-ncbi-v1
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - genes
  - autosomal-dominant
  - disease
  - Berg_et_al
  - AD
  - OMIM
  - gene_coordinates
  - CDS-regions
  summary: 'CDS region genomic coordinates, along with the compliment coordinates,
    for OMIM disease genes (as of June 2011) deemed to follow autosomal dominant inheritance.
    (Assembled by Macarthur Lab). Berg et al, 2013:  (https://www.ncbi.nlm.nih.gov/pubmed/22995991).'
  tags:
    data-provider: berg
    data-version: 1-15-2013
    file-type:
    - bed
    final-file-sizes:
      hg38-autosomal-dominant-genes-berg-v1.bed.gz: 132.42K
      hg38-autosomal-dominant-genes-berg-v1.bed.gz.tbi: 26.78K
      hg38-autosomal-dominant-genes-berg-v1.compliment.bed.gz: 79.83K
      hg38-autosomal-dominant-genes-berg-v1.compliment.bed.gz.tbi: 25.45K
    final-files:
    - hg38-autosomal-dominant-genes-berg-v1.bed.gz
    - hg38-autosomal-dominant-genes-berg-v1.bed.gz.tbi
    - hg38-autosomal-dominant-genes-berg-v1.compliment.bed.gz
    - hg38-autosomal-dominant-genes-berg-v1.compliment.bed.gz.tbi
    genomic-coordinate-base: 0-based-inclusive
    ggd-channel: genomics
